

build: 
	gcc skip_list_implementation.c run_skip.c -o skip_exec
	gcc avl_implementation.c run_avl.c -o avl_exec


run-p1:
	command time ./avl_exec

run-p2:
	command time ./skip_exec
run-best:


clean:
	rm avl_exec
	rm skip_exec